#! /bin/bash

export SRC_FOLDER="$HOME/projetos/admintools/src/*"
export BIN_FOLDER="$HOME/.local/bin/"

if [ ! -d "${BIN_FOLDER}" ]; then
  mkdir -p "${BIN_FOLDER}"
fi

for filename in ${SRC_FOLDER}
  do
    find -L "$BIN_FOLDER" -maxdepth 1 -type l -delete
    ln -sf "${filename}" "${BIN_FOLDER}"
  done

chmod u+rwx "${BIN_FOLDER}"
