#!/bin/bash

export DOTFILES=$HOME/.dotfiles
export TEMP_CONFIG="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
export CONFIG_COMM="alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'"

if [[ ! -d "${DOTFILES}" ]]; then

    git clone --bare git@github.com:ispmarin/dotfiles.git "$DOTFILES"

fi

# grep -qxF "${CONFIG_COMM}" "${HOME}/.bashrc" || echo "${CONFIG_COMM}" >> "${HOME}/.bashrc"


TEMP_CONFIG stash
TEMP_CONFIG stash branch `hostname`
TEMP_CONFIG push `hostname`

TEMP_CONFIG checkout
TEMP config status.showUntrackedFiles no
