#!/bin/bash

REPO=git@github.com:ispmarin/dotfiles.git
BRANCH=master

git init
git remote add origin $REPO

git config --local status.showUntrackedFiles no
echo '/**' >> .git/info/exclude
echo '/**' >> .gitignore; git add -f .gitignore

git push -u origin HEAD

git fetch --set-upstream origin $BRANCH
git switch --no-overwrite-ignore $BRANCH 
git switch -f $BRANCH