#!/bin/bash
USERNAME="<username>"
PASSWORD="<password>"
HOSTNAME="<FQDN>"

# Resolve current public IP
IP=$( dig +short myip.opendns.com @resolver1.opendns.com )
# Update Google DNS Record
URL="https://${USERNAME}:${PASSWORD}@domains.google.com/nic/update?hostname=${HOSTNAME}&myip=${IP}"
curl -s $URL
echo " done."
