#! /bin/bash
# $ mkvenv myvirtualenv # creates venv
# $ venv myvirtualenv   # activates venv
# $ deactivate          # deactivates venv
# $ rmvenv myvirtualenv # removes venv

export VENV_HOME="$HOME/.local/lib/venv"
[[ -d $VENV_HOME ]] || mkdir "$VENV_HOME"

lsvenv() {
  ls -1 "$VENV_HOME"
}

venv() {
  if [ $# -eq 0 ]
    then
      echo "Please provide venv name"
    else
      source "$VENV_HOME/$1/bin/activate"
  fi
}

mkvenv() {
  if [ $# -eq 0 ]
    then
      echo "Please provide venv name"
    else
      python3 -m venv "$VENV_HOME"/$1
  fi
}

rmvenv() {
  if [ $# -eq 0 ]
    then
      echo "Please provide venv name"
    else
      rm -rf "${VENV_HOME:?}"/"$1"
  fi
}

upvenv() {
  if [ $# -eq 0 ]
    then
      echo "Please provide venv name"
    else
      pip3 list --root "${VENV_HOME}" --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install --root "${VENV_HOME}" -U
  fi
}

#complete -W "$(lsvenv)" venv
