#!/usr/bin/env bash

SOURCE=/etc
TARGET=/srv/backup/osaka/etc
TODAY=$(date +%Y-%m-%d)

rsync -avAXEWSlHh --no-compress --info=progress2 --delete "${SOURCE}"  "${TARGET}-${TODAY}/" --link-dest="${TARGET}-last/"

ln -nsf "${TARGET}-${TODAY}" "${TARGET}-last"

exit 0