#!/usr/bin/env bash

export SRC_FOLDER="$HOME/profissional/projetos/admintools/src/*"
export BIN_FOLDER="$HOME/.local/bin/"

if [ ! -d "${BIN_FOLDER}" ]; then
  mkdir -p "${BIN_FOLDER}"
fi

for filename in ${SRC_FOLDER}
  do
    cp -rf "${filename}" "${BIN_FOLDER}"
  done

chmod u+rwx "${BIN_FOLDER}/*"
